[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)d)
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers = 
    regression
    desktop
    mobile
    feature(name): 기능/섹션 이름 (예: '01. API 카테고리')